name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el repositorio
      - uses: actions/checkout@v4

      # Paso 2: Instalar dependencias y construir el proyecto Angular
      - run: npm install && npm run build --if-present
        working-directory: Govench 

      # Paso 3: Desplegar el proyecto en Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOVENCH_FB742 }}  
          projectId: govench-fb742  
          channelId: live  
          entryPoint: Govench 
          working-directory: Govench 